dist: bionic
language: python
sudo: false
cache:
  pip: true
  directories:
  - eggs
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
addons:
  apt:
    packages:
    - libsasl2-dev
    - libssl-dev
    - libdb-dev
before_install:
  - pip install --upgrade pip setuptools zc.buildout coveralls createcoverage
install:
  - buildout -N -t 3 -c travis.cfg
script:
  - bin/coverage run --source=./src/node/ext/ldap --omit=./src/node/ext/ldap/main.py bin/test
after_success:
  - bin/coveralls
