language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
addons:
  apt:
    packages:
    - libsasl2-dev
    - libssl-dev
    - libdb-dev
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout coveralls createcoverage
install:
  - ./bin/buildout -N -t 3 -c travis.cfg
script:
  - ./bin/test
after_success:
  - bin/coverage run --source=./src/node/ext/ldap bin/test
  - bin/coveralls
